import standingsJson from '@data/standings.json'
import type { ConstructorStandingEntry, DriverStandingEntry, Standings } from '../model'

const standings = standingsJson as Standings

/**
 * Returns the precomputed standings from `data/standings.json`.
 * Generated by `scripts/buildStandings.ts`; never recomputed in the browser.
 */
export const getStandings = (): Standings => standings

/** Drivers' championship table, already sorted by position. */
export const getDriverStandings = (): DriverStandingEntry[] => standings.drivers

/** Constructors' championship table, already sorted by position. */
export const getConstructorStandings = (): ConstructorStandingEntry[] =>
  standings.constructors

/**
 * Looks up one driver's standings row.
 * @param driverId A driver id such as `DRV001`.
 */
export const getDriverStanding = (driverId: string): DriverStandingEntry | undefined =>
  standings.drivers.find((entry) => entry.driverId === driverId)

/** Round numbers included in the current standings, ascending. */
export const getRoundsCompleted = (): number[] => standings.roundsCompleted
